### ISSUE TITLE
Decoder is not a function

### ISSUE THREAD

**Issue by Kaliph** [evs-broadcast/node-emberplus#19]
When trying to read a emberfile using your example.

`// Simple packet decoder
const Decoder = require('emberplus').DecodeBuffer;
const fs = require("fs");

fs.readFile("tree.ember", (e,data) => {
   var root = Decoder(data);
});`

I get following Error.

C:\project\digital-ocean\modules\ember-plus.js:35
    var root = Decoder(data);
               ^
TypeError: Decoder is not a function
    at ReadFileContext.fs.readFile [as callback] (C:\project\digital-ocean\modules\ember-plus.js:35:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

**Comment by manuc66** [comment]
Hi @Kaliph,

The sample on the README is indeed not up to date, if you're stuck you might have a look at [test/DeviceTree.test.js](https://github.com/evs-broadcast/node-emberplus/blob/master/test/DeviceTree.test.js) for a working sample.

**Comment by Kaliph** [comment]
Thanks for pointing me to the test. Ok I think I have to use Decoder instead of DecodeBuffer. When I use Decoder, I get an error saying "data must be a node Buffer" what am I doing wrong? Any help would be appreciated. Thankyou

`const Decoder = require('emberplus').Decoder;
const fs = require("fs");

fs.readFile("tree.ember", (e,data) => {
var root = Decoder(data);
});`

C:\project\digital-ocean\node_modules\node-emberplus-master\node_modules\asn1\lib\ber\reader.js:17
    throw new TypeError('data must be a node Buffer');
    ^

TypeError: data must be a node Buffer
    at ExtendedReader.Reader (C:\project\digital-ocean\node_modules\node-emberplus-master\node_modules\asn1\lib\ber\reader.js:17:11)
    at new ExtendedReader (C:\project\digital-ocean\node_modules\node-emberplus-master\ber.js:71:27)
    at DecodeBuffer (C:\project\digital-ocean\node_modules\node-emberplus-master\device.js:67:15)
    at ReadFileContext.fs.readFile [as callback] (C:\project\digital-ocean\modules\ember-plus.js:37:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

**Comment by Kaliph** [comment]
Thanks it´s working now.
