### ISSUE TITLE
unhandled error event

### ISSUE THREAD

**Issue by Kaliph** [evs-broadcast/node-emberplus#22]
When there is no device available to connect, I get an unhandled error event. The same happens when I stop the Ember device and it should disconnect.

Error when no device available
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:9092
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error when disconnect device
Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)

My Code looks like this.

`var root;
var tree = new DeviceTree("localhost", 9092);
tree.connect()
.then(() => {

return tree.getDirectory();
})
.then((r) => {
root = r ;
return tree.expand(r.elements[0]);
})
.then((data) => {
console.log(data);
console.log(tree);

})
.catch((err) => {

});`

**Comment by dufourgilles** [comment]
We have seen as well but decided not to change this behavior.
[gdufour@localhost emberTest]$ node test.js 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:9000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

The problem is that the tree reject with an error but also emits an error.
Therefore, you need to catch the emitted error to avoid the crash.
[gdufour@localhost emberTest]$ vi test.js 
[gdufour@localhost emberTest]$ node test.js 
{ Error: connect ECONNREFUSED 127.0.0.1:9000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9000 }
Error: connect ECONNREFUSED 127.0.0.1:9000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
[gdufour@localhost emberTest]$ cat test.js 
const DeviceTree = require('emberplus').DeviceTree;
var root;
var tree = new DeviceTree("127.0.0.1", 9000);
**tree.on("error", (err) => { console.log(err); });**
tree.connect().then(() => {
   console.log("done"); 
}).catch((e) => {
   console.log(e.stack);
});
[gdufour@localhost emberTest]$

**Comment by Kaliph** [comment]
Thanks that helped!
